source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#inhibit_all_warnings!
use_frameworks!

target 'StockCarBroadcastRemainder' do
  pod 'DynamicButton', '~> 3.1.0'

  target 'StockCarBroadcastRemainderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StockCarBroadcastRemainderUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
