# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'StockCarBroadcastRemainder' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StockCarBroadcastRemainder

  target 'StockCarBroadcastRemainderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StockCarBroadcastRemainderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
